import { z } from "zod";
import { safeParseAIResponse, AISafeResult } from "@/shared/lib/ai/safe-ai-parser";

/**
 * Schema for an individual task generated by AI.
 * Coerces positions if the model delivers them as numeric strings.
 */
export const AiTaskSchema = z.object({
  title: z
    .string()
    .trim()
    .min(1, "El título de la tarea no puede estar vacío")
    .max(200, "El título de la tarea no puede exceder 200 caracteres"),
  position: z.coerce
    .number()
    .int("La posición de la tarea debe ser un número entero")
    .min(0, "La posición de la tarea no puede ser negativa"),
});

/**
 * Strict schema for AI-generated projects.
 * Intercepts LLM outputs before they touch Convex mutations or UI state.
 */
export const AiProjectSchema = z.object({
  projectName: z
    .string()
    .trim()
    .min(3, "El nombre del proyecto debe tener al menos 3 caracteres")
    .max(100, "El nombre del proyecto no puede exceder 100 caracteres"),
  description: z
    .string()
    .trim()
    .max(1000, "La descripción no puede exceder 1000 caracteres")
    .default(""),
  tasks: z
    .array(AiTaskSchema)
    .min(1, "El proyecto debe contener al menos 1 tarea generada")
    .max(10, "El proyecto no puede contener más de 10 tareas generadas por solicitud"),
});

/**
 * Inferred TypeScript types from the Zod schemas
 */
export type AiTask = z.infer<typeof AiTaskSchema>;
export type AiProject = z.infer<typeof AiProjectSchema>;

/**
 * Client-side boundary function: Intercepts, strips markdown fences,
 * and validates raw LLM output against AiProjectSchema before any Convex mutation.
 *
 * @param rawResponse - Raw string or parsed object returned by the AI provider
 * @returns AISafeResult<AiProject> - Discriminated union indicating success or validation issues
 */
export function validateAiProjectResponse(rawResponse: unknown): AISafeResult<AiProject> {
  return safeParseAIResponse(AiProjectSchema, rawResponse);
}
